public enum Actions
{
    SHAPE1_ACTION1,
    SHAPE1_ACTION2,
    SHAPE1_ACTION3,
    SHAPE2_ACTION1,
    SHAPE2_ACTION2,
    SHAPE2_ACTION3,
    SHAPE3_ACTION1,
    SHAPE3_ACTION2,
    SHAPE3_ACTION3
}
