public enum Actions
{
    SHAPECHANGE_TSURU,
    SHAPECHANGE_CAT,
    SHAPECHANGE_FROG,
    TSURU_ACTION1 = 10,
    TSURU_ACTION2,
    CAT_ACTION1 = 20,
    CAT_ACTION2,
    FROG_ACTION1 = 30,
    FROG_ACTION2,
    KARP_ACTION1 = 40,
    KARP_ACTION2
}
